name: Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'scripts/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - '*.cmake'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'scripts/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - '*.cmake'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir output
          cd output
          cmake .. -A x64
          cmake --build .
